# Generated by Django 5.2.5 on 2025-08-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dog'),
    ]

    operations = [
    ]
