# Generated by Django 5.2.5 on 2025-08-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250819_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='data',
        ),
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(default='brown', max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
